import { useRef, useState } from 'react';
import { Check, Pause, Play, RotateCcw, X } from 'lucide-react';
import { runningCount, shoe, trueCount, uniqueId, type PhysicalCard } from '../engine/cards';
import { useApp } from '../data/store';
import type { HiLoConfig } from '../data/schema';
import { Card, preloadCards } from '../components/Card';
import { Button, Field, Heading, NumberField, Progress, Stat } from '../components/ui';
import { useExposure } from '../hooks/useExposure';
import { useShortcuts } from '../hooks/useShortcuts';
import { SpeedControl } from './MemoryScreen';
interface CountRound { key: string; cards: PhysicalCard[]; number: number; target: number; remaining: number; reset: boolean; eligible: boolean; elapsed: number }
function CountExposure({ round, interval, onDone, onExit }: { round: CountRound; interval: number; onDone: (v: { elapsed: number; eligible: boolean }) => void; onExit: () => void }) {
  const c = useExposure(round.cards.length, interval, onDone);
  useShortcuts({ ' ': c.paused ? c.resume : c.pause, escape: onExit });
  return <section className="memorize"><div className="exposure-top"><div className="row"><Button onClick={c.paused ? c.resume : c.pause}>{c.paused ? <Play size={17} /> : <Pause size={17} />}{c.paused ? 'Pokračovat' : 'Pauza'}</Button><Button className="icon" variant="ghost" aria-label="Ukončit počítání" onClick={onExit}><X size={18} /></Button></div><span className="mono muted">{c.index + 1} / {round.cards.length} · otázka {round.number}</span></div><div className="exposure-progress"><Progress value={c.fraction * 100} /></div><div className="exposure-content">{c.paused ? <div className="empty"><Card back size="stage" /><h2>Pozastaveno</h2><p>Po pokračování dokončíš kolo jako cvičení.</p><Button variant="primary" onClick={c.resume}>Pokračovat</Button></div> : <Card id={round.cards[c.index].id} back={!c.ready} size="stage" />}</div><div className="exposure-bottom"><span className="eyebrow">Drž průběžný count v hlavě</span></div></section>;
}
export default function CountingScreen({ onExit }: { onExit: () => void }) {
  const store = useApp(), [config, setConfig] = useState(store.data.settings.hilo), [phase, setPhase] = useState<'setup' | 'ready' | 'exposure' | 'answer' | 'result' | 'done'>('setup');
  const [round, setRound] = useState<CountRound | null>(null), [answer, setAnswer] = useState(''), [correct, setCorrect] = useState(false), [error, setError] = useState(''), [loading, setLoading] = useState(false), [totals, setTotals] = useState({ correct: 0, total: 0 });
  const shoeRef = useRef<PhysicalCard[]>([]), cursor = useRef(0), count = useRef(0), began = useRef(0), guard = useRef(false);
  function update(patch: Partial<HiLoConfig>) { setConfig(c => ({ ...c, ...patch, difficulty: patch.difficulty ?? 'custom' })); }
  function prepare(number: number) {
    let reset = false;
    if (cursor.current >= shoeRef.current.length) { shoeRef.current = shoe(config.decks); cursor.current = 0; count.current = config.start; reset = true; }
    const cards = shoeRef.current.slice(cursor.current, cursor.current + config.checkpoint); cursor.current += cards.length;
    count.current = runningCount(cards, count.current);
    const next = { key: uniqueId(), cards, number, target: count.current, remaining: shoeRef.current.length - cursor.current, reset, eligible: true, elapsed: 0 };
    setRound(next); setAnswer(''); guard.current = false; setPhase(reset || number === 1 ? 'ready' : 'exposure');
  }
  async function start() {
    setLoading(true); setError('');
    try { await preloadCards(); await store.update(s => ({ ...s, settings: { ...s.settings, hilo: config } })); shoeRef.current = shoe(config.decks); cursor.current = 0; count.current = config.start; setTotals({ correct: 0, total: 0 }); prepare(1); }
    catch (e) { setError(e instanceof Error ? e.message : 'Karty se nepodařilo načíst.'); }
    finally { setLoading(false); }
  }
  const target = round ? config.kind === 'running' ? round.target : trueCount(round.target, round.remaining) : null;
  function submit() {
    if (!round || guard.current || !answer.trim() || !Number.isFinite(Number(answer)) || (config.kind === 'running' && !Number.isInteger(Number(answer)))) return;
    guard.current = true; const ok = target !== null && Math.abs(Number(answer) - target) < (config.kind === 'true' ? .051 : .0001);
    setCorrect(ok); setTotals(t => ({ correct: t.correct + Number(ok), total: t.total + 1 })); setPhase('result');
    void store.addSession({ mode: 'hilo', correct: Number(ok), total: 1, durationMs: round.elapsed + performance.now() - began.current, memorizeMs: round.elapsed, count: round.cards.length, intervalMs: config.interval, eligible: round.eligible, variant: config.kind, summary: `${config.decks} balíčků · ${config.kind === 'running' ? 'running count' : 'true count'}` });
  }
  function next() { if (!round || round.number >= config.rounds) setPhase('done'); else prepare(round.number + 1); }
  useShortcuts({ ' ': phase === 'setup' ? () => void start() : phase === 'ready' ? () => setPhase('exposure') : phase === 'result' ? next : undefined, enter: phase === 'answer' ? submit : phase === 'result' ? next : undefined, escape: phase === 'setup' ? onExit : () => setPhase('setup') });
  if (phase === 'exposure' && round) return <CountExposure key={round.key} round={round} interval={config.interval} onExit={() => setPhase('setup')} onDone={v => { setRound(r => r && { ...r, elapsed: v.elapsed, eligible: v.eligible }); began.current = performance.now(); if (config.kind === 'true' && round.remaining === 0) { setPhase('result'); setAnswer(''); setCorrect(false); } else setPhase('answer'); }} />;
  if (phase === 'done') return <div className="page narrow empty"><Check size={42} className="gold" /><h1>Počítání dokončeno</h1><p className="score-large mono">{totals.correct} / {totals.total}</p><p>Správně zodpovězené kontrolní otázky. Počet pokračoval mezi otázkami až do výměny balíčku.</p><div className="row wrap"><Button onClick={() => setPhase('setup')}>Nastavení</Button><Button variant="primary" onClick={() => void start()}><RotateCcw size={17} /> Nový trénink</Button></div></div>;
  if (phase === 'setup') return <div className="page narrow"><Heading title="Hi-Lo počítání" description="Sleduj karty a udržuj průběžný součet. Mezi otázkami count pokračuje, při novém shoe se výslovně resetuje." back={onExit} /><div className="stack"><div className="hilo-legend"><div><strong className="success mono">+1</strong><span>2, 3, 4, 5, 6</span></div><div><strong className="mono">0</strong><span>7, 8, 9</span></div><div><strong className="error mono">−1</strong><span>10, J, Q, K, A</span></div></div>{error && <p className="notice danger" role="alert">{error}</p>}<div className="panel stack"><Field label="Obtížnost"><select value={config.difficulty} onChange={e => { const difficulty = e.target.value as HiLoConfig['difficulty']; update(difficulty === 'beginner' ? { difficulty, interval: 1500, checkpoint: 5 } : difficulty === 'regular' ? { difficulty, interval: 700, checkpoint: 15 } : difficulty === 'fast' ? { difficulty, interval: 200, checkpoint: 26 } : { difficulty }); }}><option value="beginner">Začátečník</option><option value="regular">Pokročilý</option><option value="fast">Rychlý trénink</option><option value="custom">Vlastní</option></select></Field><div className="fields"><NumberField label="Počáteční count" value={config.start} min={-100} max={100} onChange={start => update({ start })} /><NumberField label="Počet balíčků" value={config.decks} min={1} max={8} onChange={decks => update({ decks })} /><NumberField label="Karet před otázkou" value={config.checkpoint} min={1} max={52} onChange={checkpoint => update({ checkpoint })} /><NumberField label="Počet otázek" value={config.rounds} min={1} max={100} onChange={rounds => update({ rounds })} /></div><SpeedControl value={config.interval} onChange={interval => update({ interval })} /><Field label="Co počítat"><select value={config.kind} onChange={e => update({ kind: e.target.value as HiLoConfig['kind'] })}><option value="running">Průběžný running count</option><option value="true">True count — přepočet na zbývající balíčky</option></select></Field>{config.kind === 'true' && <p className="notice">True count = running count ÷ počet zbývajících balíčků. Počet zbývajících karet dostaneš u otázky. Odpovídej na jedno desetinné místo.</p>}</div><Button variant="primary" wide disabled={loading} onClick={() => void start()}><Play size={18} />{loading ? 'Připravuji karty…' : 'Spustit počítání'}</Button></div></div>;
  if (!round) return null;
  if (phase === 'ready') return <div className="page narrow empty"><Card back size="large" /><h1>{round.reset ? 'Nový shoe' : 'Připraveno k počítání'}</h1><p>Začínáš na countu <strong className="mono">{config.start >= 0 ? '+' : ''}{config.start}</strong>. {config.decks} {config.decks === 1 ? 'balíček' : 'balíčků'}, první otázka po {round.cards.length} kartách.</p><Button variant="primary" onClick={() => setPhase('exposure')}><Play size={18} /> Začít rozdávání</Button></div>;
  const unavailable = config.kind === 'true' && target === null;
  return <div className="page narrow"><Heading title={phase === 'answer' ? config.kind === 'running' ? 'Jaký je průběžný count?' : 'Jaký je true count?' : unavailable ? 'Shoe je prázdný' : correct ? 'Správný count.' : 'Zkontroluj svůj součet.'} description={`Otázka ${round.number}/${config.rounds} · ${round.cards.length} nových karet`} back={() => setPhase('setup')} /><div className="stack"><div className="panel center"><span className="eyebrow">Zbývá v balíčku</span><h2 className="mono">{round.remaining} karet · {(round.remaining / 52).toFixed(2)} balíčku</h2></div>{phase === 'answer' ? <form className="stack" onSubmit={e => { e.preventDefault(); submit(); }}><Field label={config.kind === 'running' ? 'Tvůj count (celé číslo)' : 'Tvůj true count (jedno desetinné místo)'}><input className="count-input mono" autoFocus type="number" step={config.kind === 'running' ? 1 : .1} value={answer} onChange={e => setAnswer(e.target.value)} placeholder="0" required /></Field><Button type="submit" variant="primary" disabled={!answer.trim()}>Vyhodnotit <Check size={18} /></Button></form> : <>{unavailable ? <p className="notice">Při nule zbývajících balíčků není true count definovaný. Running count je <strong>{round.target}</strong>. Tato otázka se nehodnotí.</p> : <div className="stats-grid"><Stat label="Správně" value={config.kind === 'true' ? target!.toFixed(1) : target} /><Stat label="Tvoje odpověď" value={answer} /><Stat label="Running count" value={round.target} /></div>}<p className="muted">{config.kind === 'true' && target !== null ? `${round.target} ÷ ${(round.remaining / 52).toFixed(2)} = ${target.toFixed(1)}. ` : ''}Při další otázce navazuješ na průběžný součet {round.target}; vynuluje se až při novém shoe.</p><div className="context-sequence">{round.cards.map(c => <Card key={c.uid} id={c.id} size="small" />)}</div><Button variant="primary" onClick={next}>{round.number < config.rounds ? 'Další otázka' : 'Dokončit'} <Play size={18} /></Button></>}</div></div>;
}
