import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, ChevronLeft, ChevronRight, GraduationCap, Save, Search, Trash2, X } from 'lucide-react';
import { CARD_IDS, card, cardName, shuffled, type CardId, type Suit } from '../engine/cards';
import { blankAssociation, configured, configuredFields, FIELD_NAMES, PAO_FIELDS, paoCounts, reverseMatches, scorePao, type Association, type PaoField } from '../engine/pao';
import { useApp } from '../data/store';
import { Card } from '../components/Card';
import { RecallPicker, SuitFilter } from '../components/RecallPicker';
import { Button, Field, Heading, Progress, Stat } from '../components/ui';
import { useShortcuts } from '../hooks/useShortcuts';
type View = 'library' | 'editor' | 'learn' | 'forward' | 'reverse';
export default function PaoScreen() {
  const store = useApp(), data = store.data.pao, counts = paoCounts(data);
  const [view, setView] = useState<View>('library'), [filter, setFilter] = useState<Suit | 'all'>('all'), [search, setSearch] = useState(''), [status, setStatus] = useState<'all' | 'missing' | 'partial' | 'complete'>('all');
  const [index, setIndex] = useState(0), [draft, setDraft] = useState<Association>(blankAssociation), [dirty, setDirty] = useState(false), [saved, setSaved] = useState(false), [busy, setBusy] = useState(false);
  const [queue, setQueue] = useState<CardId[]>([]), [testIndex, setTestIndex] = useState(0), [revealed, setRevealed] = useState(false), [answer, setAnswer] = useState<Partial<Record<PaoField, string>>>({}), [reverseAnswer, setReverseAnswer] = useState<(CardId | null)[]>([null]);
  const [feedback, setFeedback] = useState<ReturnType<typeof scorePao> | null>(null), [reverseOk, setReverseOk] = useState<boolean | null>(null), [score, setScore] = useState({ correct: 0, total: 0 }), [finished, setFinished] = useState(false);
  const began = useRef(performance.now()), submitted = useRef(false);
  const id = CARD_IDS[index], configuredIds = CARD_IDS.filter(id => configured(data[id]));
  const activeId = queue[testIndex], activeEntry = activeId ? data[activeId] : undefined;
  const pendingDraft = useRef<{ id: CardId; draft: Association; dirty: boolean }>({ id, draft, dirty });
  pendingDraft.current = { id, draft, dirty: view === 'editor' && dirty };
  useEffect(() => () => {
    const pending = pendingDraft.current;
    if (pending.dirty) void useApp.getState().savePao(pending.id, pending.draft);
  }, []);
  useEffect(() => { window.scrollTo({ top: 0 }); }, [view, finished]);
  function edit(next: number) { setIndex(next); setDraft(data[CARD_IDS[next]] ?? blankAssociation()); setDirty(false); setSaved(false); setView('editor'); }
  async function save() { setBusy(true); const ok = await store.savePao(id, draft); setBusy(false); if (ok && pendingDraft.current.id === id && pendingDraft.current.draft === draft) { setDirty(false); setSaved(true); } return ok; }
  async function move(next: number) { if (dirty && !await save()) return; edit((next + 52) % 52); }
  async function back() { if (dirty && !await save()) return; setView('library'); }
  function begin(next: 'learn' | 'forward' | 'reverse') { if (!configuredIds.length) return; setQueue(shuffled(configuredIds)); setTestIndex(0); setRevealed(next !== 'learn'); setFeedback(null); setReverseOk(null); setAnswer({}); setReverseAnswer([null]); setScore({ correct: 0, total: 0 }); setFinished(false); submitted.current = false; began.current = performance.now(); setView(next); }
  function next() { if (testIndex + 1 >= queue.length) { setFinished(true); return; } setTestIndex(i => i + 1); setFeedback(null); setReverseOk(null); setAnswer({}); setReverseAnswer([null]); setRevealed(false); submitted.current = false; began.current = performance.now(); }
  function submit() {
    if (!activeEntry || submitted.current || view === 'learn') return;
    if (view === 'reverse' && !reverseAnswer[0]) return;
    submitted.current = true;
    const details = scorePao(activeEntry, answer);
    const reverseCorrect = view === 'reverse' && reverseMatches(data, activeEntry).includes(reverseAnswer[0]!);
    const correct = view === 'reverse' ? Number(reverseCorrect) : details.filter(d => d.correct).length, total = view === 'reverse' ? 1 : details.length;
    setFeedback(details); setReverseOk(reverseCorrect); setScore(s => ({ correct: s.correct + correct, total: s.total + total }));
    void store.addSession({ mode: 'pao', correct, total, durationMs: performance.now() - began.current, eligible: true, variant: view, pao: { cardId: activeId, correct: correct === total } });
  }
  useShortcuts({ arrowleft: view === 'editor' ? () => void move(index - 1) : undefined, arrowright: view === 'editor' ? () => void move(index + 1) : undefined, escape: view === 'editor' ? () => void back() : view !== 'library' ? () => setView('library') : undefined, ' ': view === 'learn' ? () => revealed ? next() : setRevealed(true) : undefined, enter: view === 'forward' || view === 'reverse' ? feedback ? next : submit : undefined });
  if (view === 'editor') return <div className="page narrow"><Heading title="Tvůj obraz pro tuto kartu" description="Vyplň osobu, akci, předmět nebo libovolnou kombinaci. Stačí jedna asociace." back={() => void back()} /><div className="pao-edit-hero"><Card id={id} size="large" /><div className="stack"><h2>{cardName(id)}</h2><span className={`badge ${configured(draft) ? 'gold' : ''}`}>{configuredFields(draft).length === 3 ? 'Kompletní PAO' : configured(draft) ? 'Částečné PAO' : 'Zatím bez asociace'}</span><p className="muted">Vyber něco osobního a výrazného. Asociace si můžeš postupně doplňovat.</p></div></div>
    <form className="stack" onSubmit={e => { e.preventDefault(); void save(); }}>{PAO_FIELDS.map(field => <Field key={field} label={`${FIELD_NAMES[field]} · volitelné`}><input disabled={busy || store.readonly} autoComplete="off" maxLength={500} value={draft[field]} placeholder={field === 'person' ? 'Koho ti karta připomíná?' : field === 'action' ? 'Co dělá?' : 'S jakým předmětem?'} onChange={e => { setDraft(d => ({ ...d, [field]: e.target.value })); setDirty(true); setSaved(false); }} /></Field>)}<div className="row wrap between"><Button variant="ghost" disabled={busy || store.readonly} onClick={async () => { const cleared = blankAssociation(); setDraft(cleared); setBusy(true); const ok = await store.savePao(id, cleared); setBusy(false); setDirty(!ok); setSaved(ok); }}><Trash2 size={17} /> Vymazat asociace</Button><Button type="submit" variant="primary" disabled={busy || store.readonly}><Save size={17} />{busy ? 'Ukládám…' : 'Uložit'}</Button></div><div aria-live="polite" className="save-status">{saved ? <span className="success row"><Check size={17} /> Asociace uložena</span> : dirty ? <span className="muted">Rozpracované změny · při odchodu z editoru se uloží.</span> : <span className="muted">Šipky ← → přepínají karty, když nepíšeš do pole.</span>}</div></form>
    <div className="pao-pagination"><Button disabled={busy} onClick={() => void move(index - 1)}><ChevronLeft size={16} /> Předchozí</Button><div className="grow center"><small className="mono muted">{index + 1} / 52</small><Progress value={index + 1} max={52} /></div><Button disabled={busy} onClick={() => void move(index + 1)}>Další <ChevronRight size={16} /></Button></div></div>;
  if (view !== 'library') {
    if (finished) return <div className="page narrow empty"><GraduationCap size={42} className="gold" /><h1>{view === 'learn' ? 'Prošel/prošla jsi všechny asociace.' : 'PAO trénink dokončen'}</h1>{view !== 'learn' && <p className="mono score-large">{score.correct} / {score.total}</p>}<p>{view === 'learn' ? 'Teď zkus vybavit asociace bez nápovědy.' : 'Výsledky jednotlivých karet jsou uložené v přehledu pokroku.'}</p><div className="row wrap"><Button onClick={() => setView('library')}>Zpět do knihovny</Button><Button variant="primary" onClick={() => begin(view === 'learn' ? 'forward' : view)}>Nový test <ArrowRight size={18} /></Button></div></div>;
    if (!activeEntry) return <div className="page empty"><h2>Nejdřív si nastav alespoň jednu kartu.</h2><Button onClick={() => setView('library')}>Otevřít knihovnu</Button></div>;
    const hasFeedback = feedback !== null;
    return <div className="page narrow"><Heading title={view === 'learn' ? 'Učení PAO' : view === 'reverse' ? 'Asociace → karta' : 'Karta → asociace'} description={`Karta ${testIndex + 1} z ${queue.length} · testují se pouze tvoje vyplněná pole.`} back={() => setView('library')} /><div className="stack"><Progress value={testIndex} max={queue.length} />
      {view !== 'reverse' && <div className="query-card"><Card id={activeId} size="large" /></div>}
      {view === 'learn' && <><div className="association-reveal panel">{revealed ? configuredFields(activeEntry).map(field => <div key={field}><span className="eyebrow">{FIELD_NAMES[field]}</span><p>{activeEntry[field]}</p></div>) : <><BookOpen className="gold" size={26} /><p>Vybav si vlastní asociaci, potom ji odkryj.</p></>}</div><Button variant="primary" wide onClick={() => revealed ? next() : setRevealed(true)}>{revealed ? 'Další karta' : 'Odkrýt asociaci'} <ArrowRight size={18} /></Button></>}
      {view === 'forward' && <form className="stack" onSubmit={e => { e.preventDefault(); hasFeedback ? next() : submit(); }}>{configuredFields(activeEntry).map(field => {
        const detail = feedback?.find(d => d.field === field);
        return <div className="stack field-answer" key={`${activeId}:${field}`}><Field label={FIELD_NAMES[field]}><input maxLength={500} autoComplete="off" autoFocus={field === configuredFields(activeEntry)[0]} disabled={hasFeedback} value={answer[field] ?? ''} onChange={e => setAnswer(a => ({ ...a, [field]: e.target.value }))} /></Field>{detail && <p className={`feedback-line ${detail.correct ? 'success' : 'error'}`}>{detail.correct ? <Check size={18} /> : <X size={18} />}<span>{detail.correct ? 'Správně' : `Správná odpověď: ${detail.expected}`}</span></p>}</div>;
      })}<Button type="submit" variant="primary" wide>{hasFeedback ? 'Další karta' : 'Vyhodnotit'} {hasFeedback ? <ArrowRight size={18} /> : <Check size={18} />}</Button></form>}
      {view === 'reverse' && <><div className="panel association-reveal">{configuredFields(activeEntry).map(field => <div key={field}><span className="eyebrow">{FIELD_NAMES[field]}</span><p>{activeEntry[field]}</p></div>)}</div>{!hasFeedback ? <><RecallPicker answer={reverseAnswer} onChange={setReverseAnswer} /><Button variant="primary" disabled={!reverseAnswer[0]} onClick={submit}>Vyhodnotit <Check size={18} /></Button></> : <><div className={`notice ${reverseOk ? '' : 'danger'}`}><p className={reverseOk ? 'success' : 'error'}>{reverseOk ? 'Správně. Tahle asociace patří k vybrané kartě.' : `Tato asociace patří ke kartě ${cardName(activeId)}.`}</p><div className="query-card"><Card id={activeId} /></div></div><Button variant="primary" onClick={next}>Další karta <ArrowRight size={18} /></Button></>}</>}
    </div></div>;
  }
  const visible = CARD_IDS.filter(id => {
    const fields = configuredFields(data[id]), q = search.trim().toLocaleLowerCase('cs');
    return (filter === 'all' || card(id).suit === filter) && (status === 'all' || status === 'missing' && fields.length === 0 || status === 'partial' && fields.length > 0 && fields.length < 3 || status === 'complete' && fields.length === 3) && (!q || [cardName(id), ...PAO_FIELDS.map(f => data[id]?.[f] ?? '')].join(' ').toLocaleLowerCase('cs').includes(q));
  });
  return <div className="page"><Heading title="PAO knihovna" description="52 karet. 52 osobních obrazů. Postav si vlastní systém osoby, akce a předmětu." /><div className="stack"><div className="stats-grid"><Stat label="Nastaveno" value={`${counts.configured} / 52`} /><Stat label="Kompletní PAO" value={counts.complete} /><Stat label="Částečné" value={counts.partial} /><Stat label="Zbývá" value={counts.missing} /></div><div className="row wrap"><Button disabled={!configuredIds.length} onClick={() => begin('learn')}><BookOpen size={18} /> Učit se</Button><Button variant="primary" disabled={!configuredIds.length} onClick={() => begin('forward')}><GraduationCap size={18} /> Test asociací</Button><Button disabled={!configuredIds.length} onClick={() => begin('reverse')}><ArrowLeft size={18} /> Opačný test</Button></div>{!configuredIds.length && <p className="notice">Začni první kartou níže. Stačí vyplnit jediné pole; pak můžeš rovnou spustit učení i test.</p>}<SuitFilter value={filter} onChange={setFilter} /><div className="fields"><label className="search-field"><Search size={18} /><input aria-label="Hledat kartu nebo asociaci" placeholder="Hledat kartu nebo asociaci…" value={search} onChange={e => setSearch(e.target.value)} /></label><select aria-label="Stav asociací" value={status} onChange={e => setStatus(e.target.value as typeof status)}><option value="all">Všechny stavy</option><option value="missing">Bez asociací</option><option value="partial">Částečné PAO</option><option value="complete">Kompletní PAO</option></select></div>
    <div className="pao-grid">{visible.map(id => { const entry = data[id], n = configuredFields(entry).length; return <button type="button" className={`pao-tile ${n ? 'configured' : ''}`} key={id} onClick={() => edit(CARD_IDS.indexOf(id))} aria-label={`Upravit ${cardName(id)}, ${n === 3 ? 'kompletní' : n ? 'částečné' : 'chybí'}`}><Card id={id} size="tiny" decorative /><div className="pao-tile-text"><span className={`badge ${n === 3 ? 'success' : n ? 'gold' : ''}`}>{n === 3 ? 'Kompletní' : n ? 'Částečné' : 'Chybí'}</span>{n ? configuredFields(entry).map(field => <span key={field} title={entry![field]}>{entry![field]}</span>) : <small className="muted">Přidat asociaci</small>}</div></button>; })}</div>{!visible.length && <div className="empty"><Search size={26} /><h2>Žádná karta neodpovídá filtru.</h2><Button onClick={() => { setSearch(''); setStatus('all'); setFilter('all'); }}>Zobrazit všechny karty</Button></div>}
  </div></div>;
}
