import { lazy, Suspense } from 'react';
import { Activity, ArrowRight, Trophy } from 'lucide-react';
import { useApp } from '../data/store';
import { accuracy, dateKey, latestMastery, modeStats, streak } from '../engine/progress';
import { paoCounts } from '../engine/pao';
import { MODES } from '../data/schema';
import { Button, Heading, percentage, Progress, seconds, Stat } from '../components/ui';
import { NAMES, type Route } from '../navigation';
const ActivityChart = lazy(() => import('../components/ActivityChart'));
export default function ProgressScreen({ navigate }: { navigate: (r: Route) => void }) {
  const { data } = useApp(), configured = paoCounts(data.pao).configured, mastery = latestMastery(data.sessions, data.pao);
  const records = [...data.sessions].sort((a, b) => b.createdAt - a.createdAt), totalTime = data.sessions.reduce((n, r) => n + r.durationMs, 0);
  const chart = Array.from({ length: 14 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 13 + i); const records = data.sessions.filter(r => dateKey(r.createdAt) === dateKey(+d)); return { date: d.toLocaleDateString('cs', { day: 'numeric', month: 'numeric' }), rounds: records.length, accuracy: accuracy(records) }; });
  return <div className="page"><Heading title="Tvůj pokrok" description="Skutečné výsledky, malé kroky a rekordy, které sis odtrénoval/a." /><div className="stack"><div className="stats-grid"><Stat label="Dokončená kola" value={data.sessions.length} /><Stat label="Přesnost odpovědí" value={percentage(accuracy(data.sessions))} /><Stat label="Čas tréninku" value={`${Math.round(totalTime / 60000)} min`} /><Stat label="Pravidelnost" value={`${streak(data.sessions)} dní`} /></div>
    {!records.length ? <section className="panel empty"><Activity size={36} className="gold" /><h2>První výsledek teprve přijde.</h2><p>Dokonči libovolný trénink. Tady pak uvidíš přesnost, aktivitu a své nejlepší výkony.</p><Button variant="primary" onClick={() => navigate('sequence')}>Začít první trénink <ArrowRight size={18} /></Button></section> : <section className="panel stack"><h2>Posledních 14 dní</h2><Suspense fallback={<p className="muted">Připravuji přehled aktivity…</p>}><ActivityChart data={chart} /></Suspense></section>}
    <div className="fields"><div className="panel stack"><h2>PAO systém</h2><div className="row between"><span>Nastavené asociace</span><strong className="mono">{configured} / 52</strong></div><Progress value={configured} max={52} /><div className="row between"><span>Poslední test správně</span><strong className="mono">{mastery} / 52</strong></div><p className="muted"><small>Každé kartě se počítá výsledek jejího posledního dokončeného testu.</small></p></div><div className="panel stack"><h2>Úroveň sekvence</h2><div className="row between"><strong className="score-large mono gold">{data.progression.level}</strong><Trophy size={30} className="gold" /></div><Progress value={data.progression.level} max={52} /><p className="muted">{data.progression.enabled ? `${data.progression.streak} / ${data.progression.required} bezchybných kol do dalšího zvýšení o ${data.progression.increment}.` : 'Postupné zvyšování si zapneš v nastavení Sekvence.'}</p><Button onClick={() => navigate('sequence')}>Přizpůsobit trénink</Button></div></div>
    <section className="stack"><h2>Výsledky podle režimu</h2><div className="mode-stats">{MODES.map(mode => { const s = modeStats(data.sessions, mode); return <div className="panel mode-stat" key={mode}><div className="row between"><h3>{NAMES[mode]}</h3><span className="mono gold">{percentage(s.accuracy)}</span></div><p className="muted"><small>{s.rounds} dokončených kol{['sequence', 'shuffle', 'visual', 'missing'].includes(mode) && s.best ? ` · nejlepší rozsah ${s.best}` : ''}{s.fastest ? ` · nejrychlejší bezchybné kolo ${seconds(s.fastest)}/karta` : ''}</small></p></div>; })}</div><p className="muted"><small>Rychlostní rekordy vyžadují bezchybné kolo bez přerušení. Rekordy sekvence, míchání a vizuální paměti se počítají z úplného vybavení. Přesnost stolu hodnotí volbu tahů, výhry a prohry se ukládají zvlášť v historii.</small></p></section>
    <section className="stack"><h2>Historie tréninků</h2>{records.length ? <div className="history-list">{records.slice(0, 100).map(record => <div className="history-row" key={record.id}><div><strong>{NAMES[record.mode]}</strong><small>{new Date(record.createdAt).toLocaleString('cs', { day: 'numeric', month: 'numeric', hour: '2-digit', minute: '2-digit' })}{record.count ? ` · ${record.count} karet` : ''}{record.outcome ? ` · ${record.outcome}` : ''}</small>{record.summary && <small>{record.summary}</small>}</div><span className={`mono ${record.total && record.correct === record.total ? 'success' : 'muted'}`}>{record.total ? `${record.correct}/${record.total}` : 'Bez rozhodnutí'}</span></div>)}</div> : <p className="muted">Zatím žádný dokončený trénink.</p>}{records.length > 100 && <p className="muted">Zobrazeno posledních 100 záznamů. Úplná historie je v exportu zálohy.</p>}</section>
  </div></div>;
}
