import { useRef, useState } from 'react';
import { Check, Download, HardDrive, Keyboard, RefreshCw, Upload } from 'lucide-react';
import { useApp } from '../data/store';
import { parseImport, type Snapshot } from '../data/schema';
import { paoCounts } from '../engine/pao';
import { Button, Heading, Modal, NumberField } from '../components/ui';
export function downloadJson(value: unknown, name = 'counting-cards-backup') {
  const url = URL.createObjectURL(new Blob([JSON.stringify(value, null, 2)], { type: 'application/json' }));
  const a = document.createElement('a'); a.href = url; a.download = `${name}-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export default function SettingsScreen() {
  const store = useApp(), input = useRef<HTMLInputElement>(null), [incoming, setIncoming] = useState<Snapshot | null>(null), [message, setMessage] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function fileSelected(file?: File) { if (!file) return; setError(''); try { if (file.size > 25_000_000) throw new Error('Záloha je větší než 25 MB.'); setIncoming(parseImport(await file.text())); } catch (e) { setError(e instanceof Error ? e.message : 'Zálohu se nepodařilo přečíst.'); } finally { if (input.current) input.current.value = ''; } }
  async function importData() { if (!incoming) return; setBusy(true); const ok = await store.importData(incoming); setBusy(false); if (ok) { setIncoming(null); setMessage('Záloha byla sloučena s tvými daty.'); } }
  return <div className="page narrow"><Heading title="Nastavení a zálohy" description="Přizpůsob si trénink a měj svůj PAO systém bezpečně po ruce." /><div className="stack">{message && <p className="notice success" role="status"><Check size={17} /> {message}</p>}{error && <p className="notice danger" role="alert">{error}</p>}
    <section className="panel stack"><h2 className="row"><HardDrive size={21} className="gold" /> Tvoje data</h2><p>Asociace i pokrok jsou uložené v tomto prohlížeči na tomto zařízení. Pro přenos jinam nebo vlastní zálohu si stáhni soubor.</p><div className="row wrap"><span className="badge">{paoCounts(store.data.pao).configured} PAO karet</span><span className="badge">{store.data.sessions.length} výsledků</span><span className="badge">{store.backend}</span></div><div className="row wrap"><Button variant="primary" onClick={() => { downloadJson(store.data); setMessage('Záloha byla připravena ke stažení.'); }}><Download size={17} /> Exportovat zálohu</Button><Button disabled={store.readonly} onClick={() => input.current?.click()}><Upload size={17} /> Importovat zálohu</Button><input ref={input} type="file" accept="application/json,.json" className="sr-only" aria-label="Soubor zálohy" onChange={e => void fileSelected(e.target.files?.[0])} /></div><p className="muted"><small>Aplikace při každém uložení zachovává předchozí platnou verzi pro obnovu. Staženou zálohu si ponech i mimo prohlížeč; data mezi zařízeními se automaticky nesynchronizují.</small></p>{store.error && <><p className="notice danger">{store.error}</p>{!store.readonly && <Button onClick={() => void store.update(s => s)}><RefreshCw size={17} /> Zkusit uložit znovu</Button>}</>}{store.raw !== undefined && <Button onClick={() => downloadJson(store.raw, 'counting-cards-original-data')}>Stáhnout původní obsah</Button>}{store.recovery && <Button variant="primary" onClick={async () => { if (await store.recover()) setMessage('Poslední platná verze byla obnovena.'); }}>Obnovit poslední platnou verzi</Button>}</section>
    <section className="panel stack"><h2>Trénink podle tebe</h2><label className="check"><input type="checkbox" checked={store.data.settings.motion} disabled={store.readonly} onChange={e => void store.update(s => ({ ...s, settings: { ...s.settings, motion: e.target.checked } }))} />Jemné animace rozhraní</label><p className="muted"><small>Nastavení omezení pohybu v systému má vždy přednost. Animace nikdy neprodlužují dobu zobrazení karty.</small></p><NumberField label="Denní cíl dokončených kol" value={store.data.settings.dailyGoal} min={1} max={100} onChange={dailyGoal => void store.update(s => ({ ...s, settings: { ...s.settings, dailyGoal } }))} /></section>
    <section className="panel stack"><h2 className="row"><Keyboard size={22} className="gold" /> Klávesové zkratky</h2><div className="shortcut-grid"><span><kbd>Space</kbd> Start / pauza / pokračovat</span><span><kbd>Enter</kbd> Odeslat / další kolo</span><span><kbd>R</kbd> Opakovat paměťové kolo</span><span><kbd>Esc</kbd> Zpět / ukončit kolo</span><span><kbd>←</kbd> <kbd>→</kbd> Předchozí / další PAO karta</span><span><kbd>H</kbd> <kbd>S</kbd> <kbd>D</kbd> <kbd>P</kbd> Tahy blackjacku</span></div><p className="muted"><small>Při psaní do pole mají přednost běžné klávesy. Karty lze ovládat i klávesnicí: Tab vybere pozici nebo kartu, Enter ji aktivuje.</small></p></section>
    <section className="panel stack"><h2>O aplikaci</h2><p>Counting Cards je osobní trénink paměti, PAO asociací a blackjackových dovedností. Bez účtu, plateb a skutečných sázek.</p><p className="muted"><small>Karty: <a href="https://github.com/hayeah/playing-cards-assets" target="_blank" rel="noreferrer">Playing Cards Assets</a>, původní public-domain ilustrace. Ikony Lucide. Písma Fraunces, DM Sans a DM Mono. <a href="/asset-credits.txt" target="_blank" rel="noreferrer">Licence a zdroje</a>.</small></p></section>
    <Modal open={!!incoming} onOpenChange={open => { if (!open) setIncoming(null); }} title="Sloučit zálohu" description="Soubor byl ověřen. Import doplní asociace a výsledky; ostatní karty a tvé nastavení zachová.">{incoming && <div className="stack"><p>Záloha obsahuje <strong>{paoCounts(incoming.pao).configured} nastavených karet</strong> a <strong>{incoming.sessions.length} výsledků</strong>.</p><p className="muted">U stejné karty se použije novější záznam podle data úpravy. Duplicitní výsledky se nepřidají podruhé.</p><div className="row wrap"><Button onClick={() => setIncoming(null)}>Zrušit</Button><Button variant="primary" disabled={busy} onClick={() => void importData()}>{busy ? 'Importuji…' : 'Sloučit data'}</Button></div></div>}</Modal>
  </div></div>;
}
