import { useEffect, useState } from 'react';
import { Settings2 } from 'lucide-react';
import { type Rules } from '../engine/blackjack';
import { Button, Field, Modal } from './ui';
export function RulesDialog({ rules, onApply, locked = false }: { rules: Rules; onApply: (rules: Rules) => void; locked?: boolean }) {
  const [open, setOpen] = useState(false), [draft, setDraft] = useState(rules);
  useEffect(() => { if (open) setDraft(rules); }, [open, rules]);
  return <><Button onClick={() => setOpen(true)}><Settings2 size={17} /> Pravidla</Button><Modal open={open} onOpenChange={setOpen} title="Pravidla blackjacku" description="Americký blackjack s kontrolou dealerovy skryté karty. Základní strategie bez odchylek podle countu."><div className="stack">{locked && <p className="notice">Aktuální ruka používá tato pravidla. Změnit je můžeš po jejím dohrání; změna připraví nový shoe.</p>}<fieldset className="rules-fieldset stack" disabled={locked}><Field label="Počet balíčků"><div className="chips">{([1, 2, 4, 6, 8] as const).map(decks => <button type="button" className="chip mono" key={decks} aria-pressed={draft.decks === decks} onClick={() => setDraft(d => ({ ...d, decks }))}>{decks}</button>)}</div></Field><Field label="Dealer na měkkých 17"><select value={draft.h17 ? 'h17' : 's17'} onChange={e => setDraft(d => ({ ...d, h17: e.target.value === 'h17' }))}><option value="s17">Stojí — S17</option><option value="h17">Bere kartu — H17</option></select></Field><Field label="Kdy lze zdvojnásobit"><select value={draft.double} onChange={e => setDraft(d => ({ ...d, double: e.target.value as Rules['double'] }))}><option value="any">Libovolné dvě karty</option><option value="9-11">Pouze součet 9–11</option><option value="10-11">Pouze součet 10–11</option><option value="none">Zdvojnásobení není povolené</option></select></Field>
      {([{ key: 'das', label: 'Zdvojnásobení po splitu (DAS)' }, { key: 'surrender', label: 'Pozdní vzdání (late surrender)' }, { key: 'resplit', label: 'Opakované rozdělení páru' }, { key: 'resplitAces', label: 'Opakované rozdělení es' }] as const).map(({ key, label }) => <label className="check" key={key}><input type="checkbox" checked={draft[key]} onChange={e => setDraft(d => ({ ...d, [key]: e.target.checked }))} />{label}</label>)}<Field label="Nejvyšší počet rukou po rozdělení"><select value={draft.maxHands} onChange={e => setDraft(d => ({ ...d, maxHands: Number(e.target.value) as Rules['maxHands'] }))}>{[2, 3, 4].map(n => <option key={n}>{n}</option>)}</select></Field></fieldset><p className="muted"><small>Rozdělená esa dostanou jednu kartu. Stejně hodnotné desítkové karty lze rozdělit. Blackjack před splitem má poměr 3:2. Všechny jednotky jsou pouze tréninkové.</small></p><div className="row wrap"><Button onClick={() => setOpen(false)}>Zavřít</Button>{!locked && <Button variant="primary" onClick={() => { onApply(draft); setOpen(false); }}>Použít pravidla</Button>}</div></div></Modal></>;
}
